# Python CircleCI 2.0 configuration file
version: 2

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - sonarcloud/scan
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m unittest discover

