version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
            python3 -m coverage run -m unittest
            python3 -m coverage report
  sonar:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo

      - sonarcloud/scan:
          sonar_token_variable_name: SONAR_TOKEN

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  ci:
    jobs:
      - build
      - sonar:
          requires:
            - build