# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # get repo
      - checkout 
      # virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install -r requirements.txt
      - run:
          name: "Scanning by the Sonar Tool" 
          command: | 
            echo "Running  the scanning ..."  
            ./sonar_run.sh
      # run linter (SCA) and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m unittest discover